package importer.suppliers.summit;

import java.util.HashMap;
import java.util.Map;

class SumCarMapper {
    private Map<String, String> makeMap;
    private Map<String, String> modelMap;
    private Map<String, String> subModelMap;

    String getCorrectMake(String make) {
        return makeMap.get(make);
    }

    SumCarMapper() {
       makeMap = getMakeMap();
       modelMap = getModelMap();
       subModelMap = getSubModelMap();
    }

    private Map<String, String> getSubModelMap() {
        Map<String, String> result = new HashMap<>();
        result.put("hybrid xle premium", "Hybrid XLE Premium");
        result.put("jls","JLS");
        result.put("jls plus","JLS Plus");
        result.put("jlx plus","JLX Plus");
        result.put("jlx plus se","JLX Plus SE");
        result.put("jls plus se","JLS Plus SE");
        result.put("js plus","JS Plus");
        result.put("jx plus","JX Plus");
        result.put("jx se","JX SE");
        result.put("le eco", "LE Eco");
        result.put("le eco plus", "LE Eco Plus");
        result.put("limited x", "Limited X");
        result.put("se sport", "SE Sport");
        result.put("s-runner", "S-Runner");
        result.put("ultimate adventure edition","Ultimate Adventure Edition");
        result.put("xl-7","XL-7");
        result.put("xl-7 limited","XL-7 Limited");
        result.put("xl-7 plus","XL-7 Plus");
        result.put("xl-7 touring","XL-7 Touring");
        result.put("xle premium", "XLE Premium");
        result.put("xle touring", "XLE Touring");
        result.put("xle touring se", "XLE Touring SE");
        result.put("hybrid xle touring", "Hybrid XLE Touring");
        result.put("xls sport", "XLS Sport");
        result.put("xlt no boundaries", "XLT No Boundaries");
        result.put("x-runner", "X-Runner");
        result.put("xse", "XSE");
        result.put("4xe", "4xe");
        result.put("4xe rubicon", "4xe Rubicon");
        result.put("4xe sahara", "4xe Sahara");
        result.put("80th anniversary", "80th Anniversary");
        result.put("freedom", "Freedom");
        result.put("unlimited 80th anniversary", "Unlimited 80th Anniversary");
        result.put("unlimited freedom", "Unlimited Freedom");
        result.put("unlimited high altitude", "Unlimited High Altitude");
        result.put("unlimited islander", "Unlimited Islander");
        result.put("unlimited rubicon 392", "Unlimited Rubicon 392");
        result.put("unlimited sport altitude", "Unlimited Sport Altitude");
        result.put("unlimited sahara altitude", "Unlimited Sahara Altitude");
        result.put("unlimited willys", "Unlimited Willys");
        result.put("unlimited willys sport", "Unlimited Willys Sport");
        result.put("willys sport", "Willys Sport");
        result.put("gran sport", "Gran Sport");
        result.put("225 custom", "225 Custom");
        result.put("club wagon", "Club Wagon");
        result.put("custom wagon", "Custom Wagon");
        result.put("chateau wagon", "Chateau Wagon");
        result.put("type s-3", "Type S-3");
        result.put("gto", "GTO");
        result.put("pony", "Pony");
        result.put("mpg runabout", "MPG Runabout");
        result.put("runabout", "Runabout");
        result.put("s runabout", "S Runabout");
        result.put("lxxv anniversary edition", "LXXV Anniversary Edition");
        result.put("z7 gs", "Z7 GS");
        result.put("eurosport", "Eurosport");
        result.put("x-11", "X-11");
        result.put("cruiser ls", "Cruiser LS");
        result.put("ste", "STE");
        result.put("olympia limited", "Olympia Limited");
        result.put("lx brougham", "LX Brougham");
        result.put("xr5", "XR5");
        result.put("international", "International");
        result.put("value leader", "Value Leader");
        result.put("lts", "LTS");
        result.put("sts", "STS");
        result.put("z26", "Z26");
        result.put("z24", "Z24");
        result.put("etc", "ETC");
        result.put("g", "G");
        result.put("sho", "SHO");
        result.put("montana", "Montana");
        result.put("esc", "ESC");
        result.put("se comfort", "SE Comfort");
        result.put("ls premium", "LS Premium");
        result.put("warner bros.", "Warner Bros.");
        result.put("svg", "SVG");
        result.put("cx plus", "CX Plus");
        result.put("dream", "Dream");
        result.put("ls sport", "LS Sport");
        result.put("executive protection series", "Executive Protection Series");
        result.put("ultra", "Ultra");
        result.put("protection series", "Protection Series");
        result.put("ultimate l", "Ultimate L");
        result.put("sv6", "SV6");
        result.put("2", "2");
        result.put("3", "3");
        result.put("dream cruiser", "Dream Cruiser");
        result.put("street cruiser", "Street Cruiser");
        result.put("signature l", "Signature L");
        result.put("signature limited", "Signature Limited");
        result.put("gsl", "GSL");
        result.put("ultimate edition", "Ultimate Edition");
        result.put("r l.l. bean edition", "R L.L. Bean Edition");
        result.put("vdc limited", "VDC Limited");
        result.put("gtp", "GTP");
        result.put("fleet", "Fleet");
        result.put("designer series", "Designer Series");
        result.put("r vdc limited", "R VDC Limited");
        result.put("lx special edition", "LX Special Edition");
        result.put("2.5i basic", "2.5i Basic");
        result.put("2.5i l.l. bean edition", "2.5i L.L. Bean Edition");
        result.put("2.5i limited l.l. bean edition", "2.5i Limited L.L. Bean Edition");
        result.put("mainstreet", "Mainstreet");
        result.put("avp", "AVP");
        result.put("crossroad", "Crossroad");
        result.put("del ray", "Del Ray");
        result.put("futura sprint", "Futura Sprint");
        result.put("sst", "SST");
        result.put("60 special", "60 Special");
        result.put("60 special brougham", "60 Special Brougham");
        result.put("mx brougham", "MX Brougham");
        result.put("brougham ls", "Brougham LS");
        result.put("brougham lx", "Brougham LX");
        result.put("brougham sx", "Brougham SX");
        result.put("sportabout", "Sportabout");
        result.put("elite", "Elite");
        result.put("amx", "AMX");
        result.put("z7", "Z7");
        result.put("biarritz", "Biarritz");
        result.put("formal", "Formal");
        result.put("cobra", "Cobra");
        result.put("sundowner", "Sundowner");
        result.put("sundowner base", "Sundowner Base");
        result.put("sundowner dlx", "Sundowner DLX");
        result.put("sundowner se-5", "Sundowner SE-5");
        result.put("024", "024");
        result.put("cadet", "Cadet");
        result.put("pucci", "Pucci");
        result.put("024 miser", "024 Miser");
        result.put("sundowner sport", "Sundowner Sport");
        result.put("black magic", "Black Magic");
        result.put("e-type", "E-Type");
        result.put("bill blass", "Bill Blass");
        result.put("024 charger 2.2", "024 Charger 2.2");
        result.put("turismo", "Turismo");
        result.put("shelby", "Shelby");
        result.put("crimson cat", "Crimson Cat");
        result.put("cruiser lx", "Cruiser LX");
        result.put("cruiser s", "Cruiser S");
        result.put("cruiser sx", "Cruiser SX");
        result.put("turbo gt", "Turbo GT");
        result.put("xx anniversary edition", "XX Anniversary Edition");
        result.put("rs turbo", "RS Turbo");
        result.put("type-10", "Type-10");
        result.put("olympic", "Olympic");
        result.put("d'oro", "d'Oro");
        result.put("1500 s", "1500 S");
        result.put("gt-350 20th anniversary", "GT-350 20th Anniversary");
        result.put("svo", "SVO");
        result.put("lc", "LC");
        result.put("glh", "GLH");
        result.put("elan", "Elan");
        result.put("fila", "Fila");
        result.put("supreme", "Supreme");
        result.put("le limited", "LE Limited");
        result.put("5.0", "5.0");
        result.put("country squire lx", "Country Squire LX");
        result.put("crown victoria lx", "Crown Victoria LX");
        result.put("xr3", "XR3");
        result.put("mt5", "MT5");
        result.put("fx16", "FX16");
        result.put("fx", "FX");
        result.put("vl", "VL");
        result.put("sse", "SSE");
        result.put("fx16 gts", "FX16 GTS");
        result.put("america", "America");
        result.put("ls special edition", "LS Special Edition");
        result.put("dlx all trac", "DLX All Trac");
        result.put("le all trac", "LE All Trac");
        result.put("aerocoupe", "Aerocoupe");
        result.put("aerocoupe yl", "Aerocoupe YL");
        result.put("twin cam", "Twin Cam");
        result.put("2.0 si 4ws", "2.0 Si 4WS");
        result.put("2.0 si", "2.0 Si");
        result.put("2.0 s", "2.0 S");
        result.put("sei", "SEi");
        result.put("gse", "GSE");
        result.put("gtz", "GTZ");
        result.put("gsi", "GSi");
        result.put("park avenue ultra", "Park Avenue Ultra");
        result.put("euro", "Euro");
        result.put("luxury edition", "Luxury Edition");
        result.put("spring edition", "Spring Edition");
        result.put("regency elite", "Regency Elite");
        result.put("4wd", "4WD");
        result.put("trio", "Trio");
        result.put("royale ls", "Royale LS");
        result.put("se-r", "SE-R");
        result.put("lx-e", "LX-E");
        result.put("scx", "SCX");
        result.put("gst", "GST");
        result.put("gsx", "GSX");
        result.put("ssei", "SSEi");
        result.put("z34", "Z34");
        result.put("le value leader", "LE Value Leader");
        result.put("duster", "Duster");
        result.put("super coupe", "Super Coupe");
        result.put("esi", "ESi");
        result.put("jxi", "JXi");
        result.put("ve", "VE");
        result.put("acr", "ACR");
        result.put("dhs", "DHS");
        result.put("dts", "DTS");
        result.put("nautica", "Nautica");
        result.put("royale lss", "Royale LSS");
        result.put("spyder gs", "Spyder GS");
        result.put("spyder gst", "Spyder GST");
        result.put("olympic gold edition", "Olympic Gold Edition");
        result.put("ss/t 5.9l", "SS/T 5.9L");
        result.put("zx2 cool coupe", "ZX2 Cool Coupe");
        result.put("zx2 hot coupe", "ZX2 Hot Coupe");
        result.put("zx2 s/r", "ZX2 S/R");
        result.put("zx2", "ZX2");
        result.put("gt1", "GT1");
        result.put("se1", "SE1");
        result.put("se2", "SE2");
        result.put("ca", "CA");
        result.put("gxp", "GXP");
        result.put("1", "1");
        result.put("style", "Style");
        result.put("cargo", "Cargo");
        result.put("brighton", "Brighton");
        result.put("spyder gt", "Spyder GT");
        result.put("spyder gts", "Spyder GTS");
        result.put("lxi limited", "LXi Limited");
        result.put("ss 35th anniversary edition", "SS 35th Anniversary Edition");
        result.put("ss dale earnhardt signature edition", "SS Dale Earnhardt Signature Edition");
        result.put("neiman marcus", "Neiman Marcus");
        result.put("pro-am", "Pro-Am");
        result.put("l se", "L SE");
        result.put("l 35th anniversary", "L 35th Anniversary");
        result.put("ls competition", "LS Competition");
        result.put("ss high sport", "SS High Sport");
        result.put("ss pace car", "SS Pace Car");
        result.put("james bond edition", "James Bond Edition");
        result.put("maxx", "Maxx");
        result.put("maxx ls", "Maxx LS");
        result.put("maxx ss", "Maxx SS");
        result.put("maxx lt", "Maxx LT");
        result.put("maxx ltz", "Maxx LTZ");
        result.put("srt-10", "SRT-10");
        result.put("xle limited", "XLE Limited");
        result.put("pacific coast roadster", "Pacific Coast Roadster");
        result.put("red line", "Red Line");
        result.put("green line", "Green Line");
        result.put("ex special edition", "EX Special Edition");
        result.put("xs l.l. bean edition", "XS L.L. Bean Edition");
        result.put("rt", "RT");
        result.put("rtl", "RTL");
        result.put("rts", "RTS");
        result.put("lx-p", "LX-P");
        result.put("lx-s", "LX-S");
        result.put("srt-4", "SRT-4");
        result.put("sports 2.5 xt", "Sports 2.5 XT");
        result.put("sports 2.5 x", "Sports 2.5 X");
        result.put("classic lt", "Classic LT");
        result.put("hybrid-l", "Hybrid-L");
        result.put("sport v6", "Sport V6");
        result.put("sport edition", "Sport Edition");
        result.put("2.5 gt", "2.5 GT");
        result.put("1.6", "1.6");
        result.put("1.6 base", "1.6 Base");
        result.put("rush", "Rush");
        result.put("uptown", "Uptown");
        result.put("livery", "Livery");
        result.put("touring gls", "Touring GLS");
        result.put("touring se", "Touring SE");
        result.put("cxl special edition", "CXL Special Edition");
        result.put("walter p. chrysler signature series", "Walter P. Chrysler Signature Series");
        result.put("fe", "FE");
        result.put("crosscabriolet", "CrossCabriolet");
        result.put("sport limited", "Sport Limited");
        result.put("sport premium", "Sport Premium");
        result.put("1.8 s", "1.8 S");
        result.put("1.8 sl", "1.8 SL");
        result.put("1.6 s", "1.6 S");
        result.put("1.6 s plus", "1.6 S Plus");
        result.put("1.6 sl", "1.6 SL");
        result.put("1.6 sv", "1.6 SV");
        result.put("black diamond ltz", "Black Diamond LTZ");
        result.put("sxl", "SXL");
        result.put("rtx", "RTX");
        result.put("ln", "LN");
        result.put("f85", "F85");
        result.put("s-55", "S-55");
        result.put("sxl turbo", "SXL Turbo");
        result.put("sx turbo", "SX Turbo");
        result.put("sr turbo", "SR Turbo");
        result.put("fe+s", "FE+S");
        result.put("fe+sv", "FE+SV");
        result.put("american value package", "American Value Package");
        result.put("se 30th anniversary edition", "SE 30th Anniversary Edition");
        result.put("sxt 30th anniversary edition", "SXT 30th Anniversary Edition");
        result.put("30th anniversary edition", "30th Anniversary Edition");
        result.put("fuel cell", "Fuel Cell");
        result.put("limited platinum", "Limited Platinum");
        result.put("sport special edition", "Sport Special Edition");
        result.put("50th anniversary special edition", "50th Anniversary Special Edition");
        result.put("police responder", "Police Responder");
        result.put("x l.l. bean edition", "X L.L. Bean Edition");
        result.put("couture edition", "Couture Edition");
        result.put("225 limited", "225 Limited");
        result.put("warlock ii", "Warlock II");
        result.put("li'l red express", "Li'l Red Express");
        result.put("voyager ex", "Voyager EX");
        result.put("voyager ex wagon", "Voyager EX Wagon");
        result.put("griffin", "Griffin");
        result.put("sh-awd", "SH-AWD");
        result.put("2.5t awd", "2.5T AWD");
        result.put("awd", "AWD");
        result.put("x/c", "X/C");
        result.put("wrx premium", "WRX Premium");
        result.put("r1", "R1");
        result.put("r2", "R2");
        result.put("phaeton", "Phaeton");
        result.put("lx-sv", "LX-SV");
        result.put("supra", "Supra");
        result.put("boss 351", "Boss 351");
        result.put("boss 429", "Boss 429");
        result.put("grande", "Grande");
        result.put("shelby gt-350", "Shelby GT-350");
        result.put("shelby gt-500", "Shelby GT-500");
        result.put("shelby gt-500kr", "Shelby GT-500KR");
        result.put("shelby gt-350h", "Shelby GT-350H");
        result.put("cobra jet", "Cobra Jet");
        result.put("ga", "GA");
        result.put("326", "326");
        result.put("440", "440");
        result.put("mugen si", "MUGEN Si");
        result.put("mk iv", "MK IV");
        result.put("v-8", "V-8");
        result.put("rt 4wd", "RT 4WD");
        result.put("wagovan", "Wagovan");
        result.put("ventura", "Ventura");
        result.put("z/28", "Z/28");
        result.put("zl1", "ZL1");
        result.put("mc", "MC");
        result.put("super bee", "Super Bee");
        result.put("crestwood", "Crestwood");
        result.put("gran coupe", "Gran Coupe");
        result.put("custom suburban", "Custom Suburban");
        result.put("gran sedan", "Gran Sedan");
        result.put("sport suburban", "Sport Suburban");
        result.put("suburban", "Suburban");
        result.put("s-23", "S-23");
        result.put("salon", "Salon");
        result.put("sport gt", "Sport GT");
        result.put("vip", "VIP");
        result.put("super charged", "Super Charged");
        result.put("natural gas", "Natural Gas");
        result.put("si 4ws", "Si 4WS");
        result.put("type sh", "Type SH");
        result.put("rally edition", "Rally Edition");
        result.put("re:flex", "RE:FLEX");
        result.put("speciale", "Speciale");
        result.put("ti super", "TI Super");
        result.put("berlina", "Berlina");
        result.put("spider super", "Spider Super");
        result.put("spider veloce", "Spider Veloce");
        result.put("sprint speciale", "Sprint Speciale");
        result.put("sprint veloce", "Sprint Veloce");
        result.put("sprint zagato", "Sprint Zagato");
        result.put("turnpike cruiser", "Turnpike Cruiser");
        result.put("quattrovalvole", "Quattrovalvole");
        result.put("polestar", "Polestar");
        result.put("t6 polestar", "T6 Polestar");
        result.put("2.5i sport", "2.5i Sport");
        result.put("shelby gt350", "Shelby GT350");
        result.put("shelby gt350r", "Shelby GT350R");
        result.put("wl3401-3502", "WL3401-3502");
        result.put("wl3605-3706", "WL3605-3706");
        result.put("wl3707-3808", "WL3707-3808");
        result.put("wl3809-3903", "WL3809-3903");
        result.put("wl3904-4100", "WL3904-4100");
        result.put("wl4101-4300", "WL4101-4300");
        result.put("wl4204-4500", "WL4204-4500");
        result.put("2.5gt", "2.5GT");
        result.put("mikado", "Mikado");
        result.put("spx", "SPX");
        result.put("sport truck", "Sport Truck");
        result.put("wagon crg", "Wagon Crg");
        result.put("wagon dx", "Wagon DX");
        result.put("wagon le", "Wagon LE");
        result.put("1 ton", "1 Ton");
        result.put("indy 500 pace car", "Indy 500 Pace Car");
        result.put("5842-1", "5842-1");
        result.put("5842t-1", "5842T-1");
        result.put("5864-2", "5864-2");
        result.put("5864t-2", "5864T-2");
        result.put("5942-1", "5942-1");
        result.put("5942t-1", "5942T-1");
        result.put("5964-2", "5964-2");
        result.put("5964t-2", "5964T-2");
        result.put("6964-2", "6964-2");
        result.put("6984-2", "6984-2");
        result.put("6964t-2", "6964T-2");
        result.put("tc2200-2509", "TC2200-2509");
        result.put("tc2510-2700", "TC2510-2700");
        result.put("tc2701-2809", "TC2701-2809");
        result.put("tc2810-3006", "TC2810-3006");
        result.put("tc3007-3108", "TC3007-3108");
        result.put("tc3109-3400", "TC3109-3400");
        result.put("tc3401-3502", "TC3401-3502");
        result.put("tc3503-3604", "TC3503-3604");
        result.put("tc3605-3706", "TC3605-3706");
        result.put("tc3707-3808", "TC3707-3808");
        result.put("tc3809-3903", "TC3809-3903");
        result.put("tc3904-4100", "TC3904-4100");
        result.put("mclaren", "Mclaren");
        result.put("6900-0", "6900-0");
        result.put("vista", "Vista");
        result.put("vista se", "Vista SE");
        result.put("fl5042s", "FL5042S");
        result.put("fl5044s", "FL5044S");
        result.put("fl6042s", "FL6042S");
        result.put("fl6042st", "FL6042ST");
        result.put("fl6044s", "FL6044S");
        result.put("fl7042s", "FL7042S");
        result.put("fl8042s", "FL8042S");
        result.put("fl8044s", "FL8044S");
        result.put("fl8062s", "FL8062S");
        result.put("fl8062st", "FL8062ST");
        result.put("fl8064s", "FL8064S");
        result.put("fl8066s", "FL8066S");
        result.put("fl8066st", "FL8066ST");
        result.put("fl8064st", "FL8064ST");
        result.put("fl8084st", "FL8084ST");
        result.put("fl8042st", "FL8042ST");
        result.put("x/c awd", "X/C AWD");
        result.put("x/c awd se", "X/C AWD SE");
        result.put("l 30th anniversary", "L 30th Anniversary");
        result.put("limited 30th anniversary", "Limited 30th Anniversary");
        result.put("sus 30th anniversary", "SUS 30th Anniversary");
        result.put("r awd", "R AWD");
        result.put("f7b042", "F7B042");
        result.put("com2200-2509", "COM2200-2509");
        result.put("com2701-2809", "COM2701-2809");
        result.put("com2810-3006", "COM2810-3006");
        result.put("com3109-3400", "COM3109-3400");
        result.put("com3401-3502", "COM3401-3502");
        result.put("com3503-3604", "COM3503-3604");
        result.put("com3605-3706", "COM3605-3706");
        result.put("com3007-3108", "COM3007-3108");
        result.put("com3707-3808", "COM3707-3808");
        result.put("com3904-4100", "COM3904-4100");
        result.put("aac2200-2509", "AAC2200-2509");
        result.put("aac2510-2700", "AAC2510-2700");
        result.put("aac2701-2809", "AAC2701-2809");
        result.put("aac2810-3006", "AAC2810-3006");
        result.put("aac3007-3108", "AAC3007-3108");
        result.put("aac3109-3400", "AAC3109-3400");
        result.put("aac3401-3502", "AAC3401-3502");
        result.put("aac3503-3604", "AAC3503-3604");
        result.put("aac3605-3706", "AAC3605-3706");
        result.put("aac3707-3808", "AAC3707-3808");
        result.put("aac3809-3903", "AAC3809-3903");
        result.put("aac3904-4100", "AAC3904-4100");
        result.put("l.l.bean", "L.L. Bean");
        result.put("vdc", "VDC");
        result.put("m5500", "M5500");
        result.put("m6500", "M6500");
        result.put("m7500", "M7500");
        result.put("m8500", "M8500");
        result.put("cinco", "Cinco");
        result.put("h6", "H6");
        result.put("r32", "R32");
        result.put("hdx", "HDX");
        result.put("vr-x", "VR-X");
        result.put("t7f042", "T7F042");
        result.put("h6 35th anniversary edition", "H6 35th Anniversary Edition");
        result.put("h6 vdc", "H6 VDC");
        result.put("bb1800-2199", "BB1800-2199");
        result.put("bb2200-2509", "BB2200-2509");
        result.put("bb2510-2700", "BB2510-2700");
        result.put("bb2701-2809", "BB2701-2809");
        result.put("bb3007-3108", "BB3007-3108");
        result.put("bb3109-3400", "BB3109-3400");
        result.put("bb3503-3604", "BB3503-3604");
        result.put("durocross", "DuroCross");
        result.put("aero xwd", "Aero XWD");
        result.put("turbo x", "Turbo X");
        result.put("zr1", "ZR1");
        result.put("blue", "Blue");
        result.put("hybrid platinum", "Hybrid Platinum");
        result.put("denali hybrid", "Denali Hybrid");
        result.put("touring plus", "Touring Plus");
        result.put("f sport", "F Sport");
        result.put("el ssv", "EL SSV");
        result.put("limited premium", "Limited Premium");
        result.put("l.l. bean", "L.L. Bean");
        result.put("c7h064", "C7H064");
        result.put("c6c042", "C6C042");
        result.put("c6e042", "C6E042");
        result.put("c6v042", "C6V042");
        result.put("c7c042", "C7C042");
        result.put("c7e042", "C7E042");
        result.put("c7h042", "C7H042");
        result.put("c7v042", "C7V042");
        result.put("c8c042", "C8C042");
        result.put("c8c064", "C8C064");
        result.put("c8e042", "C8E042");
        result.put("c8v042", "C8V042");
        result.put("c8v064", "C8V064");
        result.put("f7b064", "F7B064");
        result.put("fl8084s", "FL8084S");
        result.put("dpl", "DPL");
        result.put("dl kammback", "DL Kammback");
        result.put("dl sx4", "DL Sx4");
        result.put("kammback", "Kammback");
        result.put("sx4", "Sx4");
        result.put("sst mark donohue", "SST Mark Donohue");
        result.put("sst trans am", "SST Trans Am");
        result.put("330", "330");
        result.put("440h", "440H");
        result.put("rogue", "Rogue");
        result.put("hurst sc/rambler", "Hurst SC/Rambler");
        result.put("r/t turbo", "R/T Turbo");
        result.put("mp3", "MP3");
        result.put("sigma", "Sigma");
        result.put("spyder sl", "Spyder SL");
        result.put("mighty mike", "Mighty Mike");
        result.put("sandpiper", "Sandpiper");
        result.put("scooter", "Scooter");
        result.put("woody", "Woody");
        result.put("cl plus", "CL Plus");
        result.put("b7t042", "B7T042");
        result.put("crown", "Crown");
        result.put("lebaron", "LeBaron");
        result.put("medallion", "Medallion");
        result.put("special coupe", "Special Coupe");
        result.put("royal brougham", "Royal Brougham");
        result.put("270", "270");
        result.put("demon", "Demon");
        result.put("demon 340", "Demon 340");
        result.put("phoenix", "Phoenix");
        result.put("sport 360", "Sport 360");
        result.put("swinger", "Swinger");
        result.put("swinger 340", "Swinger 340");
        result.put("swinger special", "Swinger Special");
        result.put("sport 340", "Sport 340");
        result.put("770", "770");
        result.put("c6h042", "C6H042");
        result.put("l", "L");
        result.put("millennium edition", "Millennium Edition");
        result.put("40 foot", "40 Foot");
        result.put("45 foot", "45 Foot");
        result.put("trofeo", "Trofeo");
        result.put("mark cross", "Mark Cross");
        result.put("es turbo", "ES Turbo");
        result.put("iroc", "Iroc");
        result.put("iroc r/t", "Iroc R/T");
        result.put("pacifica", "Pacifica");
        result.put("turbo z", "Turbo Z");
        result.put("fifth avenue", "Fifth Avenue");
        result.put("custom", "Custom");
        result.put("deluxe", "Deluxe");
        result.put("sport", "Sport");
        result.put("w3s042", "W3S042");
        result.put("w4s042", "W4S042");
        result.put("w5r042", "W5R042");
        result.put("w5s042", "W5S042");
        result.put("w5t042", "W5T042");
        result.put("mpg", "MPG");
        result.put("990", "990");
        result.put("police cruiser", "Police Cruiser");
        result.put("panel delivery", "Panel Delivery");
        result.put("si alb", "Si ALB");
        result.put("wide track", "Wide Track");
        result.put("wide track chief", "Wide Track Chief");
        result.put("wide track golden eagle", "Wide Track Golden Eagle");
        result.put("wide track laredo", "Wide Track Laredo");
        result.put("wide track limited", "Wide Track Limited");
        result.put("mark ii", "Mark II");
        result.put("gs sport", "GS Sport");
        result.put("road runner", "Road Runner");
        result.put("spec", "Spec");
        result.put("special savoy", "Special Savoy");
        result.put("340", "340");
        result.put("360", "360");
        result.put("sc/360", "SC/360");
        result.put("880", "880");
        result.put("custom 400", "Custom 400");
        result.put("660", "660");
        result.put("brougham talisman", "Brougham Talisman");
        result.put("brougham commercial chassis", "Brougham Commercial Chassis");
        result.put("luxury sport", "Luxury Sport");
        result.put("v", "V");
        result.put("deville", "DeVille");
        result.put("special value", "Special Value");
        result.put("3100", "3100");
        result.put("3200", "3200");
        result.put("3600", "3600");
        result.put("3400", "3400");
        result.put("3500", "3500");
        result.put("3700", "3700");
        result.put("3800", "3800");
        result.put("3900", "3900");
        result.put("fleetmaster", "Fleetmaster");
        result.put("ppv", "PPV");
        result.put("sxt sport", "SXT Sport");
        result.put("500xl", "500XL");
        result.put("500 xl", "500 XL");
        result.put("super cobra jet", "Super Cobra Jet");
        result.put("sunliner", "Sunliner");
        result.put("victoria", "Victoria");
        result.put("grabber", "Grabber");
        result.put("hybrid ex-l", "Hybrid EX-L");
        result.put("plug-in", "Plug-In");
        result.put("travelall", "Travelall");
        result.put("travelall custom", "Travelall Custom");
        result.put("150", "150");
        result.put("200", "200");
        result.put("ss2", "SS2");
        result.put("terra", "Terra");
        result.put("traveller", "Traveller");
        result.put("xlc", "XLC");
        result.put("commando", "Commando");
        result.put("black label", "Black Label");
        result.put("lsc", "LSC");
        result.put("versace", "Versace");
        result.put("custom l", "Custom L");
        result.put("202", "202");
        result.put("404", "404");
        result.put("s-22", "S-22");
        result.put("cj", "CJ");
        result.put("spoiler", "Spoiler");
        result.put("x-100", "X-100");
        result.put("s-33", "S-33");
        result.put("spyder gs sport", "Spyder GS Sport");
        result.put("spyder se", "Spyder SE");
        result.put("oz rally", "OZ Rally");
        result.put("sportback", "Sportback");
        result.put("sportback ralliart", "Sportback Ralliart");
        result.put("gts sportback", "GTS Sportback");
        result.put("ralliart sportback", "Ralliart Sportback");
        result.put("taxi", "Taxi");
        result.put("regent", "Regent");
        result.put("sebring", "Sebring");
        result.put("sebring plus", "Sebring Plus");
        result.put("custom safari", "Custom Safari");
        result.put("custom safari transcontinental", "Custom Safari Transcontinental");
        result.put("super deluxe", "Super Deluxe");
        result.put("alpine sport", "Alpine Sport");
        result.put("outback limited", "Outback Limited");
        result.put("outdoor", "Outdoor");
        result.put("sun sport", "Sun Sport");
        result.put("sx premium", "SX Premium");
        result.put("xsport", "XSport");
        result.put("std", "STD");
        result.put("ez", "EZ");
        result.put("traveler", "Traveler");
        result.put("satellite", "Satellite");
        result.put("custom s-55", "Custom S-55");
        result.put("bicentenial edition", "Bicentenial Edition");
        result.put("xfi", "XFi");
        result.put("club victoria", "Club Victoria");
        result.put("starliner", "Starliner");
        result.put("town victoria", "Town Victoria");
        result.put("95", "95");
        result.put("lakewood", "Lakewood");
        result.put("monza", "Monza");
        result.put("monza spyder", "Monza Spyder");
        result.put("touring elite", "Touring Elite");
        result.put("scamp", "Scamp");
        result.put("sr5 all trac", "SR5 All Trac");
        result.put("cdx", "CDX");
        result.put("c f sport", "C F Sport");
        result.put("gt turbo", "GT Turbo");
        result.put("l awd", "L AWD");
        result.put("lx awd", "LX AWD");
        result.put("gs awd", "GS AWD");
        result.put("ls awd", "LS AWD");
        result.put("lts awd", "LTS AWD");
        result.put("sport awd", "Sport AWD");
        result.put("xr5 awd", "XR5 AWD");
        result.put("silver anniversary", "Silver Anniversary");
        result.put("sun valley", "Sun Valley");
        result.put("srt8 core", "Srt8 Core");
        result.put("ces", "Ces");
        result.put("cls", "Cls");
        result.put("clx", "Clx");
        result.put("csx", "Csx");
        result.put("shelby z", "Shelby Z");
        result.put("signet", "Signet");
        result.put("glx plus", "Glx Plus");
        result.put("appearance", "Appearance");
        result.put("designers' accent edition", "Designers' Accent Edition");
        result.put("road hawk", "Road Hawk");
        result.put("cosworth", "Cosworth");
        result.put("panel express", "Panel Express");
        result.put("firenza", "Firenza");
        result.put("gt safari", "GT Safari");
        result.put("sj safari", "SJ Safari");
        result.put("s safari", "S Safari");
        result.put("2+2 sport", "2+2 Sport");
        result.put("2+2 spyder", "2+2 Spyder");
        result.put("lemans", "LeMans");
        result.put("mirage", "Mirage");
        result.put("towne coupe", "Towne Coupe");
        result.put("towne coupe cabriolet", "Towne Coupe Cabriolet");
        result.put("towne coupe sport", "Towne Coupe Sport");
        result.put("towne coupe spyder", "Towne Coupe Spyder");
        result.put("high altitude 4xe", "High Altitude 4xe");
        result.put("rubicon 4xe", "Rubicon 4xe");
        result.put("unlimited rubicon 4xe", "Unlimited Rubicon 4xe");
        result.put("sahara 4xe", "Sahara 4xe");
        result.put("unlimited sahara 4xe", "Unlimited Sahara 4xe");
        result.put("unlimited high altitude 4xe", "Unlimited High Altitude 4xe");
        result.put("limited longhorn", "Limited Longhorn");
        result.put("longhorn", "Longhorn");
        result.put("pro", "Pro");
        result.put("elevation standard", "Elevation Standard");
        result.put("mojave", "Mojave");
        result.put("midnight edition", "Midnight Edition");
        result.put("c3", "C3");
        result.put("trx launch edition", "TRX Launch Edition");
        result.put("1-ton", "1-Ton");
        result.put("463", "463");
        result.put("473", "473");
        result.put("cj-2", "CJ-2");
        result.put("cj-3", "CJ-3");
        result.put("cj-5", "CJ-5");
        result.put("cj-6", "CJ-6");
        result.put("dj-3", "DJ-3");
        result.put("fj", "FJ");
        result.put("jeepster", "Jeepster");
        result.put("sedan delivery", "Sedan Delivery");
        result.put("truck", "Truck");
        result.put("utility wagon", "Utility Wagon");
        result.put("whb", "WBH");
        result.put("m38a1", "M38A1");
        result.put("big bend", "Big Bend");
        result.put("black diamond", "Black Diamond");
        result.put("outer banks", "Outer Banks");
        result.put("n/a", "Base");
        result.put("unlimited high tide", "Unlimited High Tide");
        result.put("esv", "ESV");
        result.put("ext", "EXT");



        //submodel
        return result;
    }

    private Map<String, String> getModelMap() {
        Map<String, String> result = new HashMap<>();
        result.put("land rover","Land Rover"); //old land rovers 1948-1974
        result.put("hi-lux","Hi-Lux");
        result.put("lj80","LJ80");
        result.put("navara","Navara");
        result.put("triton","Triton");
        result.put("drover","Drover");
        result.put("amarok","Amarok");
        result.put("samurai","Samurai");
        result.put("b series", "B Series");
        result.put("bt-50", "BT-50");
        result.put("master 85", "Master 85");
        result.put("special deluxe", "Special Deluxe");
        result.put("dj", "DJ");
        result.put("fleetmaster", "Fleetmaster");
        result.put("stylemaster series", "Stylemaster Series");
        result.put("styleline deluxe", "Styleline Deluxe");
        result.put("styleline special", "Styleline Special");
        result.put("nomad", "Nomad");
        result.put("commuter", "Commuter");
        result.put("ranch wagon", "Ranch Wagon");
        result.put("cb300", "CB300");
        result.put("60 special", "60 Special");
        result.put("commercial chassis", "Commercial Chassis");
        result.put("tr3a", "TR3A");
        result.put("tr3b", "TR3B");
        result.put("tr4", "TR4");
        result.put("tr6", "TR6");
        result.put("tr250", "TR250");
        result.put("tr4a", "TR4A");
        result.put("dino 206 gt", "Dino 206 GT");
        result.put("dino 246 gt", "Dino 246 GT");
        result.put("dino 246 gts", "Dino 246 GTS");
        result.put("xke", "XKE");
        result.put("xk140", "XK140");
        result.put("xk120", "XK120");
        result.put("mgb", "MGB");
        result.put("k2", "K2");
        result.put("k3", "K3");
        result.put("mountain master", "Mountain Master");
        result.put("2.4", "2.4");
        result.put("3.4", "3.4");
        result.put("3.8", "3.8");
        result.put("Sovereign", "Sovereign");
        result.put("mark vii", "Mark VII");
        result.put("mark viii", "Mark VIII");
        result.put("mark ix", "Mark IX");
        result.put("420", "420");
        result.put("xc", "XC");
        result.put("xc formed rail", "XC Formed Rail");
        result.put("xc lowered rail", "XC Lowered Rail");
        result.put("xc modular rail", "XC Modular Rail");
        result.put("xc raised rail", "XC Raised Rail");
        result.put("xc straight rail", "XC Straight Rail");
        result.put("affinity", "Affinity");
        result.put("allure", "Allure");
        result.put("inspire", "Inspire");
        result.put("intrigue", "Intrigue");
        result.put("magna", "Magna");
        result.put("alpine", "Alpine");
        result.put("giulietta", "Giulietta");
        result.put("308 gtb", "308 GTB");
        result.put("308 gtbi", "308 GTBi");
        result.put("308 gts", "308 GTS");
        result.put("308 gtsi", "308 GTSi");
        result.put("gt6", "GT6");
        result.put("spitfire", "Spitfire");
        result.put("365 gt4 bb", "365 GT4 BB");
        result.put("wanderlodge", "Wanderlodge");
        result.put("500e", "500E");
        result.put("sovereign", "Sovereign");
        result.put("4/4", "4/4");
        result.put("250", "250");
        result.put("w18", "W18");
        result.put("silver hawk", "Silver Hawk");
        result.put("lark", "Lark");
        result.put("luv", "LUV");
        result.put("hawk", "Hawk");
        result.put("avanti", "Avanti");
        result.put("gran sport", "Gran Sport");
        result.put("5800", "5800");
        result.put("5900", "5900");
        result.put("6900", "6900");
        result.put("tc2000", "TC2000");
        result.put("l8000f", "L8000F");
        result.put("l9000", "L9000");
        result.put("ln7000", "LN7000");
        result.put("ln8000", "LN8000");
        result.put("ln9000", "LN9000");
        result.put("lt8000f", "LT8000F");
        result.put("lt9000", "LT9000");
        result.put("lla9000", "LLA9000");
        result.put("ltla9000", "LTLA9000");
        result.put("fl50", "FL50");
        result.put("fl60", "FL60");
        result.put("fb65", "FB65");
        result.put("fl70", "FL70");
        result.put("fl80", "FL80");
        result.put("fc70", "FC70");
        result.put("fc80", "FC80");
        result.put("t7500", "T7500");
        result.put("f650", "F650");
        result.put("f750", "F750");
        result.put("commercial bus", "Commercial Bus");
        result.put("all american fe", "All American FE");
        result.put("all american re", "All American RE");
        result.put("acterra 5500", "Acterra 5500");
        result.put("acterra 6500", "Acterra 6500");
        result.put("acterra 7500", "Acterra 7500");
        result.put("acterra 8500", "Acterra 8500");
        result.put("acterra", "Acterra");
        result.put("saf-t-liner", "Saf-T-Liner");
        result.put("ce school bus", "CE School Bus");
        result.put("c8500 topkick", "C8500 Topkick");
        result.put("c7500 topkick", "C7500 Topkick");
        result.put("c6500 topkick", "C6500 Topkick");
        result.put("lnt8000f", "LNT8000F");
        result.put("lnt9000", "LNT9000");
        result.put("6900xd", "6900XD");
        result.put("c6500 kodiak", "C6500 Kodiak");
        result.put("c7500 kodiak", "C7500 Kodiak");
        result.put("c8500", "C8500");
        result.put("190sl", "190SL");
        result.put("nassau", "Nassau");
        result.put("st regis", "St Regis");
        result.put("b7", "B7");
        result.put("meadowbrook", "Meadowbrook");
        result.put("millenia", "Millenia");
        result.put("cambridge", "Cambridge");
        result.put("concord", "Concord");
        result.put("cranbrook", "Cranbrook");
        result.put("custom", "Custom");
        result.put("fleet special", "Fleet Special");
        result.put("xl2", "XL2");
        result.put("sport wagon", "Sport Wagon");
        result.put("suburban", "Suburban");
        result.put("w4500 tiltmaster", "W4500 Tiltmaster");
        result.put("w5500 tiltmaster", "W5500 Tiltmaster");
        result.put("w3500 forward", "W3500 Forward");
        result.put("w4500 forward", "W4500 Forward");
        result.put("w5500 forward", "W5500 Forward");
        result.put("series 61", "Series 61");
        result.put("p100", "P100");
        result.put("p300", "P300");
        result.put("1100", "1100");
        result.put("1500", "1500");
        result.put("Ford", "ford");
        result.put("fc170", "FC170");
        result.put("dynamic 88", "Dynamic 88");
        result.put("super 88", "Super 88");
        result.put("jetfire", "Jetfire");
        result.put("403", "403");
        result.put("404", "404");
        result.put("streamliner", "Streamliner");
        result.put("super chief", "Super Chief");
        result.put("gl-10", "GL-10");
        result.put("glf", "GLF");
        result.put("rx", "RX");
        result.put("cadenza", "Cadenza");
        result.put("truck", "Truck");
        result.put("brougham", "Brougham");
        result.put("voyager", "Voyager");
        result.put("xk150", "XK150");
        result.put("240z", "240Z");
        result.put("260z", "260Z");
        result.put("280z", "280Z");
        result.put("courier sedan delivery", "Courier Sedan Delivery");
        result.put("del rio wagon", "Del Rio Wagon");
        result.put("country cruiser", "Country Cruiser");
        result.put("medalist", "Medalist");
        result.put("corvair truck", "Corvair Truck");
        result.put("w22", "W22");
        result.put("w24", "W24");
        result.put("leganza", "Leganza");
        result.put("p20 series", "P20 Series");
        result.put("p30 series", "P30 Series");
        result.put("ford", "Ford");
        result.put("verona", "Verona");
        result.put("park lane wagon", "Park Lane Wagon");
        result.put("starliner", "Starliner");
        result.put("808", "808");
        result.put("rx-3", "RX-3");
        result.put("fiesta", "Fiesta");
        result.put("silverado 1500 ltd", "Silverado 1500 LTD");
        result.put("sierra denali", "Sierra Denali");
        result.put("sj413", "SJ413");




        //Model
        return result;
    }







    //k = incorrect, v = correct
    //makes will be always lowcase
    private Map<String, String> getMakeMap() {
        Map<String, String> result = new HashMap<>();
        result.put("santana", "Santana");
        result.put("holden", "Holden");
        result.put("spartan motors", "Spartan Motors");
        result.put("Spartan Motors", "Spartan Motors");
        result.put("daimler", "Daimler");
        result.put("ferrari", "Ferrari");
        result.put("western star", "Western Star");
        result.put("mg", "MG");
        result.put("Mack", "Mack");
        result.put("morgan", "Morgan");
        result.put("country coach motorhome", "Country Coach Motorhome");
        result.put("sterling truck", "Sterling Truck");
        result.put("thomas", "Thomas");
        result.put("ic corporation", "IC Corporation");
        result.put("prevost", "Prevost");
        result.put("workhorse custom chassis", "Workhorse Custom Chassis");

        return result;
    }

    String getCorrectModel(String model) {
        return modelMap.get(model);
    }

    String getCorrectSubModel(String subModel) {
        return subModelMap.get(subModel);
    }
}
